# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# Filesystem layout (fileSystems.*, swapDevices) is intentionally NOT
# carried in this file — it lives in flake-modules/disko.nix and is
# instantiated by the host bridge via
# `config.flake.lib.diskoLayouts.bare-metal { disk = "…"; }`. The
# disko NixOS module synthesizes `config.fileSystems.*` from
# `disko.devices` at evaluation time.
#
# When regenerating this file on real hardware, use
#   sudo nixos-generate-config --no-filesystems --show-hardware-config \
#     > hosts/pb-x1/hardware-configuration.nix
# so the fileSystems / swapDevices blocks aren't emitted (they would
# collide with the disko-generated ones).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
