# PowerShell profile — generated by the nixos flake, deployed by `hm_win`.
#
# Mirrors the WSL/zsh setup: starship prompt, zoxide, fzf, atuin,
# history-aware editing, aliases, and a `tools` cheatsheet. Targets
# PowerShell 7 (pwsh); degrades gracefully if a tool isn't installed yet
# (run the generated setup.ps1 first).
#
# Do not edit on Windows — edit flake-modules/windows/profile.ps1 and
# re-run `hm_win` in WSL. Do NOT run `nix fmt` on this file (the repo
# formatter is nixpkgs-fmt and will corrupt it).

# --- History-aware line editing (PSReadLine) ---------------------------
# Home / End / Ctrl+Left / Ctrl+Right and friends are bound by default in
# PSReadLine; we only add history prediction + history search on the
# arrows. PageUp / PageDown are intentionally left at their defaults.
if (Get-Module -ListAvailable -Name PSReadLine) {
    Import-Module PSReadLine
    Set-PSReadLineOption -PredictionSource History
    Set-PSReadLineOption -HistorySearchCursorMovesToEnd
    Set-PSReadLineKeyHandler -Key UpArrow   -Function HistorySearchBackward
    Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
}

# --- Prompt: starship (reads ~/.config/starship.toml from hm_win) ------
if (Get-Command starship -ErrorAction SilentlyContinue) {
    $ENV:STARSHIP_CONFIG = Join-Path $HOME '.config\starship.toml'
    Invoke-Expression (&starship init powershell)
}

# --- Smart cd: zoxide --------------------------------------------------
if (Get-Command zoxide -ErrorAction SilentlyContinue) {
    Invoke-Expression (& { (zoxide init powershell | Out-String) })
}

# --- Shell history: atuin (Ctrl+R only) --------------------------------
# `--disable-up-arrow` keeps the Up key as PSReadLine history search
# (recall + edit the previous command) instead of atuin hijacking Up to
# open its full-screen search UI. Ctrl+R still opens atuin.
if (Get-Command atuin -ErrorAction SilentlyContinue) {
    # atuin defaults to %APPDATA%\atuin on Windows; point it at the
    # hm_win-deployed config (~/.config/atuin/config.toml) so the
    # compact/inline style matches the WSL/zsh setup.
    $ENV:ATUIN_CONFIG_DIR = Join-Path $HOME '.config\atuin'
    Invoke-Expression (& { (atuin init powershell --disable-up-arrow | Out-String) })
    # One-time: seed atuin from PowerShell's existing PSReadLine history
    # (atuin starts empty and does not auto-absorb past history).
    $atuinMarker = Join-Path $HOME '.atuin_imported'
    if (-not (Test-Path $atuinMarker)) {
        atuin import powershell *> $null
        New-Item -ItemType File -Path $atuinMarker -Force | Out-Null
    }
}

# --- Fuzzy finder: PSFzf (Ctrl+T files, Ctrl+R history) ----------------
if (Get-Module -ListAvailable -Name PSFzf) {
    Import-Module PSFzf
    Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r'
}

# --- Aliases / functions mirroring the zsh setup -----------------------
function ll {
    if (Get-Command eza -ErrorAction SilentlyContinue) { eza -la @args } else { Get-ChildItem @args }
}
Set-Alias -Name g -Value git
function gs { git status @args }
function gd { git diff @args }
function gl { git log --oneline --graph --decorate @args }
function lg { lazygit @args }
function gdft { git -c diff.external=difft diff @args }   # structural diff

# --- tools: the terminal cheatsheet (rendered via glow) ----------------
function tools {
    $doc = Join-Path $HOME '.config\terminal-help.md'
    if ((Get-Command glow -ErrorAction SilentlyContinue) -and (Test-Path $doc)) {
        glow $doc
    } elseif (Test-Path $doc) {
        Get-Content $doc
    } else {
        Write-Host 'terminal-help.md not found - run hm_win in WSL to deploy it.'
    }
}

# --- Misc --------------------------------------------------------------
# uv installs tool shims (e.g. `vd` from visidata) into ~\.local\bin.
$uvBin = Join-Path $HOME '.local\bin'
if ((Test-Path $uvBin) -and ($Env:Path -notlike "*$uvBin*")) { $Env:Path += ";$uvBin" }

if (Get-Command nvim -ErrorAction SilentlyContinue) { $ENV:EDITOR = 'nvim' }
