# PowerShell profile — generated by the nixos flake, deployed by `hm_win`.
#
# Mirrors the WSL/zsh setup: starship prompt, zoxide, fzf, atuin,
# emacs-mode line editing, GNU coreutils (uutils), aliases, and a `tools`
# cheatsheet. Targets
# PowerShell 7 (pwsh); degrades gracefully if a tool isn't installed yet
# (run the generated setup.ps1 first).
#
# Do not edit on Windows — edit flake-modules/windows/profile.ps1 and
# re-run `hm_win` in WSL. Do NOT run `nix fmt` on this file (the repo
# formatter is nixpkgs-fmt and will corrupt it).

# --- History-aware line editing (PSReadLine) ---------------------------
# EditMode Emacs is the important one: pwsh on Windows defaults to
# EditMode Windows, which leaves Ctrl+A / Ctrl+E / Ctrl+W / Ctrl+U /
# Ctrl+K / Ctrl+Y unbound (Ctrl+A is SelectAll there). Emacs mode is the
# same set of chords zsh gives via `bindkey -e` in flake-modules/zsh.nix,
# so line editing feels identical on both sides. Home / End / Ctrl+Left /
# Ctrl+Right stay bound in either mode.
#
# Tab -> MenuComplete mirrors zsh's `menu select` (cycle through a menu of
# completions) instead of Windows mode's blind cycle-in-place.
#
# Ctrl+R is deliberately NOT set here: atuin and PSFzf both rebind it
# further down, and the last binding wins.
if (Get-Module -ListAvailable -Name PSReadLine) {
    Import-Module PSReadLine
    Set-PSReadLineOption -EditMode Emacs
    Set-PSReadLineOption -PredictionSource History
    Set-PSReadLineOption -HistorySearchCursorMovesToEnd
    Set-PSReadLineKeyHandler -Key Tab        -Function MenuComplete
    Set-PSReadLineKeyHandler -Key UpArrow   -Function HistorySearchBackward
    Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
}

# --- Prompt: starship (reads ~/.config/starship.toml from hm_win) ------
if (Get-Command starship -ErrorAction SilentlyContinue) {
    $ENV:STARSHIP_CONFIG = Join-Path $HOME '.config\starship.toml'
    Invoke-Expression (&starship init powershell)
}

# --- Smart cd: zoxide --------------------------------------------------
if (Get-Command zoxide -ErrorAction SilentlyContinue) {
    Invoke-Expression (& { (zoxide init powershell | Out-String) })
}

# --- Shell history: atuin (Ctrl+R only) --------------------------------
# `--disable-up-arrow` keeps the Up key as PSReadLine history search
# (recall + edit the previous command) instead of atuin hijacking Up to
# open its full-screen search UI. Ctrl+R still opens atuin.
if (Get-Command atuin -ErrorAction SilentlyContinue) {
    # atuin defaults to %APPDATA%\atuin on Windows; point it at the
    # hm_win-deployed config (~/.config/atuin/config.toml) so the
    # compact/inline style matches the WSL/zsh setup.
    $ENV:ATUIN_CONFIG_DIR = Join-Path $HOME '.config\atuin'
    Invoke-Expression (& { (atuin init powershell --disable-up-arrow | Out-String) })
    # One-time: seed atuin from PowerShell's existing PSReadLine history
    # (atuin starts empty and does not auto-absorb past history).
    $atuinMarker = Join-Path $HOME '.atuin_imported'
    if (-not (Test-Path $atuinMarker)) {
        atuin import powershell *> $null
        New-Item -ItemType File -Path $atuinMarker -Force | Out-Null
    }
}

# --- Fuzzy finder: PSFzf (Ctrl+T files, Ctrl+R history) ----------------
if (Get-Module -ListAvailable -Name PSFzf) {
    Import-Module PSFzf
    Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r'
}

# --- GNU coreutils (uutils-coreutils, installed via Scoop) -------------
# uutils is a Rust reimplementation of GNU coreutils compiled with MSVC:
# real native Win32 binaries, no Cygwin/MSYS runtime and no path
# translation layer. ~60 of its 85 commands have no PowerShell equivalent
# at all (head, tail, wc, cut, tr, uniq, comm, join, paste, nl, fold, seq,
# shuf, tac, split, base64, sha256sum, du, df, realpath, basename,
# dirname, env, printf, …) and light up the moment it's on PATH.
#
# The remaining dozen are SHADOWED: PowerShell resolves names in the order
# Alias > Function > Cmdlet > Application, so the built-in `ls`/`cat`/`rm`
# aliases would always beat the uutils binaries no matter where they sit
# on PATH. Removing the aliases is the only way to get GNU behaviour, so
# that's what we do — `ls -lh`, `cp -r`, `mkdir -p`, `sort -u`, `rm -rf`
# then work exactly as they do under zsh/bash.
#
# Trade-off, accepted deliberately: these commands now emit TEXT rather
# than objects. `(pwd).Path`, `mkdir x` returning a DirectoryInfo, and
# `rm -Recurse -Force` all stop working. Three escape hatches:
#   - a Visual Studio developer shell is detected and skipped (below)
#   - set $Env:PS_KEEP_ALIASES=1 before launching to skip this entirely
#   - run `Restore-PSAliases` to put them back in the current session
#
# Not touched: `cd`, `type`, `del`, `where`, `select` (no uutils command
# of that name) and `find` (uutils ships none — Windows' find.exe stays).
# uutils' `link.exe` / `expand.exe` shims are deleted by setup.ps1 so they
# can never shadow the MSVC linker on PATH.
$PSAliasesShadowedByUutils = @(
    'cat', 'cp', 'dir', 'echo', 'ls', 'mv', 'pwd', 'rm', 'rmdir', 'sleep', 'sort', 'tee'
)

# Native VC builds are safe from this either way — external compilers,
# msbuild and nmake never see PowerShell aliases, only PATH. But the
# *glue* around them is often PowerShell that assumes `mkdir -Force` /
# `rm -Recurse` resolve to the cmdlets, so a Developer PowerShell (or any
# vcvars-initialised session) keeps the stock aliases untouched.
$IsVCDevShell = [bool]($Env:VSINSTALLDIR -or $Env:VCINSTALLDIR -or
                       $Env:VCToolsInstallDir -or $Env:DevEnvDir)

# `numfmt` is a GNU-only name — a single cheap, unambiguous probe for
# "uutils is on PATH" (checking each of the 12 names would cost 12
# Get-Command lookups on every shell start).
if ((-not $Env:PS_KEEP_ALIASES) -and (-not $IsVCDevShell) -and
    (Get-Command numfmt -CommandType Application -ErrorAction SilentlyContinue)) {
    foreach ($n in $PSAliasesShadowedByUutils) {
        # -Force: several of the defaults are ReadOnly/AllScope.
        Remove-Alias -Name $n -Force -ErrorAction SilentlyContinue
    }
    # `mkdir` and `more` are FUNCTIONS in PowerShell, not aliases, so they
    # need removing from the Function: drive instead.
    foreach ($n in 'mkdir', 'more') {
        Remove-Item -Path "Function:\$n" -Force -ErrorAction SilentlyContinue
    }
}

# Undo for the current session. `mkdir`/`more` are restored as thin
# wrappers over the cmdlets they originally shelled out to.
function Restore-PSAliases {
    $map = @{
        cat = 'Get-Content'; cp = 'Copy-Item'; dir = 'Get-ChildItem'
        echo = 'Write-Output'; ls = 'Get-ChildItem'; mv = 'Move-Item'
        pwd = 'Get-Location'; rm = 'Remove-Item'; rmdir = 'Remove-Item'
        sleep = 'Start-Sleep'; sort = 'Sort-Object'; tee = 'Tee-Object'
    }
    foreach ($k in $map.Keys) { Set-Alias -Name $k -Value $map[$k] -Scope Global -Force }
    Set-Item -Path Function:Global:mkdir -Value { New-Item -ItemType Directory @args } -Force
    Set-Item -Path Function:Global:more  -Value { $input | more.com @args } -Force
    Write-Host 'PowerShell aliases restored for this session (uutils still on PATH by full name).'
}

# --- Aliases / functions mirroring the zsh setup -----------------------
function ll {
    if (Get-Command eza -ErrorAction SilentlyContinue) { eza -la @args } else { Get-ChildItem @args }
}
Set-Alias -Name g -Value git
function gs { git status @args }
function gd { git diff @args }
function gl { git log --oneline --graph --decorate @args }
function lg { lazygit @args }
function gdft { git -c diff.external=difft diff @args }   # structural diff

# btop4win is the native-Windows port of btop; expose it as `btop` to match
# Linux/mac muscle memory and terminal-help.md. winget installs it portable
# and creates an on-PATH shim named `btop.exe` (which this function shadows)
# that points at the real btop4win.exe. Resolve the real exe directly - via
# the shim if PATH already has winget's Links dir, else by searching the
# portable Packages tree - so `btop` works even in the same session that just
# installed it (before a new shell picks up the updated PATH). Config is
# deployed next to the exe by hm_win.
function btop {
    $exe = (Get-Command btop.exe -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1).Source
    if (-not $exe) {
        $exe = (Get-ChildItem "$Env:LOCALAPPDATA\Microsoft\WinGet\Packages" -Recurse -Filter btop4win.exe -ErrorAction SilentlyContinue | Select-Object -First 1).FullName
    }
    if ($exe) { & $exe @args }
    else { Write-Warning "btop4win not installed - run 'hm_win --setup' from WSL" }
}

# --- md-view / tools: Markdown rendering ------------------------------
# Mirrors the Linux `md-view` (flake-modules/markdown-viewer.nix). Read
# that file's header before changing any of this; the short version:
#
#   * glow decides whether to render Markdown from the FILE EXTENSION,
#     so anything not named *.md is copied to a .md temp file first.
#     Without this, `md-view README` prints raw source.
#   * every built-in glamour theme leaves the literal `##` markers on
#     headings, so we ship our own style (md-view-style.json, generated
#     from the same Nix definition the Linux side uses).
#   * an empty glow config is passed explicitly so a stray `glow config`
#     run can't change settings we don't set.
#   * glow's 80-column fallback mangles the wider tables, so the width
#     is measured and capped at 100.
#
# Paging: glow's --pager shells out to $env:PAGER, and Windows ships no
# usable one. NO new dependency is pulled in for this — Git for Windows
# (already a hard dependency, `Git.Git` in wingetCli) bundles GNU
# less.exe under usr\bin, and that is what we use.
#
# The two things that are NOT substitutes, so nobody "simplifies" this
# later: Windows' built-in more.com and uutils' `more` (which does come
# with uutils-coreutils) both lack a raw-control-chars option, so
# glow's ANSI would be printed literally rather than rendered.
#
# Order: anything named `less` on PATH, then Git's copy, then unpaged
# output — the one behaviour that can't be mirrored from Linux.
function md-view {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)] [string] $Path,
        [Parameter(ValueFromPipeline = $true)] [string[]] $InputObject
    )
    begin { $piped = [System.Collections.Generic.List[string]]::new() }
    process { if ($null -ne $InputObject) { $piped.AddRange($InputObject) } }
    end {
        if (-not (Get-Command glow -ErrorAction SilentlyContinue)) {
            if ($Path -and (Test-Path -LiteralPath $Path)) { Get-Content -LiteralPath $Path }
            elseif ($piped.Count) { $piped }
            else { Write-Host 'md-view: glow not installed - run the generated setup.ps1.' }
            return
        }

        $tmp = $null
        if ($piped.Count) {
            $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName() + '.md')
            Set-Content -LiteralPath $tmp -Value $piped -Encoding utf8
            $doc = $tmp
        } elseif ($Path) {
            if (-not (Test-Path -LiteralPath $Path)) {
                Write-Error "md-view: cannot read '$Path'"; return
            }
            # Only files NAMED .md are rendered; copy anything else.
            if ([System.IO.Path]::GetExtension($Path) -eq '.md') {
                $doc = (Resolve-Path -LiteralPath $Path).Path
            } else {
                $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName() + '.md')
                Copy-Item -LiteralPath $Path -Destination $tmp
                $doc = $tmp
            }
        } else {
            Write-Host 'usage: md-view <file>   (or pipe Markdown in)'
            return
        }

        $mermaidTmp = $null
        try {
            $nixwin = Join-Path $HOME '.config\nixwin'
            $style = Join-Path $nixwin 'md-view-style.json'
            $conf = Join-Path $nixwin 'md-view-glow.yml'

            # Mermaid: same conservative rules as the Linux md-view (see
            # flake-modules/markdown-viewer.nix). mermaid-ascii renders
            # sequence diagrams and square-node flowcharts correctly;
            # unsupported diagram TYPES exit non-zero, but unsupported
            # node SHAPES exit zero with a WRONG diagram, so those blocks
            # are left as source rather than shown misleadingly.
            $mmd = Join-Path $nixwin 'bin\mermaid-ascii.exe'
            $raw = Get-Content -LiteralPath $doc -Raw
            if ((Test-Path $mmd) -and ($raw -match '(?m)^(```|~~~)mermaid')) {
                $shapes = '[A-Za-z0-9_](\[\[|\[\(|\[/|\[\\|[({>])'
                # Same two-pass normalisation as the Linux md-view (see
                # flake-modules/markdown-viewer.nix for why each rule
                # exists and why the order matters). Bracket-anchored
                # shapes first, then — only if no label contains the
                # characters the remaining rules key on — the rest.
                $normBracket = @(
                    @('([A-Za-z0-9_])\[\[([^\]]*)\]\]', '$1[$2]'),
                    @('([A-Za-z0-9_])\[\(([^\]]*)\)\]', '$1[$2]'),
                    @('([A-Za-z0-9_])\[[/\\]([^\]]*)[/\\]\]', '$1[$2]')
                )
                $normRest = @(
                    @('([A-Za-z0-9_])\(\(\(([^)]*)\)\)\)', '$1[$2]'),
                    @('([A-Za-z0-9_])\(\(([^)]*)\)\)', '$1[$2]'),
                    @('([A-Za-z0-9_])\(\[([^\]]*)\]\)', '$1[$2]'),
                    @('([A-Za-z0-9_])\(([^)]*)\)', '$1[$2]'),
                    @('([A-Za-z0-9_])\{\{([^}]*)\}\}', '$1[$2]'),
                    @('([A-Za-z0-9_])\{([^}]*)\}', '$1[$2]'),
                    @('([A-Za-z0-9_])>([^\]]*)\]', '$1[$2]'),
                    @('--\s+([^->|]+[^->|\s])\s*-->', '-->|$1|'),
                    @('==\s+([^=>|]+[^=>|\s])\s*==>', '-->|$1|'),
                    @('-\.\s+([^.>|]+[^.>|\s])\s*\.->', '-->|$1|'),
                    @('==>', '-->'),
                    @('-\.->', '-->'),
                    @('(\]|[A-Za-z0-9_])\s*--[ox]\s*', '$1 --> '),
                    @('(\]|[A-Za-z0-9_])\s*---\s*([A-Za-z0-9_])', '$1 --> $2')
                )
                function Invoke-MermaidNorm([string]$t, $rules) {
                    foreach ($r in $rules) { $t = [regex]::Replace($t, $r[0], $r[1]) }
                    return $t
                }
                function Test-MermaidLabelsSimple([string]$t) {
                    foreach ($m in [regex]::Matches($t, '\[([^\]]*)\]')) {
                        if ($m.Groups[1].Value -match '[{(\[]|--|==|>') { return $false }
                    }
                    return $true
                }
                $out = [System.Text.StringBuilder]::new()
                $block = $null
                foreach ($line in ($raw -split "\r?\n")) {
                    if ($null -eq $block) {
                        if ($line -match '^(```|~~~)mermaid\s*$') { $block = @() }
                        else { [void]$out.AppendLine($line) }
                        continue
                    }
                    if ($line -match '^(```|~~~)') {
                        $src = ($block -join "`n")
                        # Strip YAML front matter; mermaid-ascii aborts
                        # with "missing graph definition" on it.
                        $bodyLines = $block
                        if (($bodyLines | Where-Object { $_.Trim() } | Select-Object -First 1) -match '^\s*---\s*$') {
                            $seen = 0; $kept = @()
                            foreach ($bl in $bodyLines) {
                                if ($seen -lt 2 -and $bl.Trim() -eq '---') { $seen++; continue }
                                if ($seen -ge 2) { $kept += $bl }
                            }
                            if ($kept.Count) { $bodyLines = $kept }
                        }
                        $body = ($bodyLines -join "`n")
                        $head = ($bodyLines | Where-Object { $_.Trim() -and $_.Trim() -notmatch '^%%' } | Select-Object -First 1)
                        if ($head -match '^\s*(graph|flowchart)') {
                            $body = Invoke-MermaidNorm $body $normBracket
                            if (Test-MermaidLabelsSimple $body) {
                                $body = Invoke-MermaidNorm $body $normRest
                            }
                        }
                        $art = $null
                        if (-not (($head -match '^\s*(graph|flowchart)') -and ($body -match $shapes))) {
                            $mtmp = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName() + '.mmd')
                            Set-Content -LiteralPath $mtmp -Value $body -Encoding utf8
                            $art = & $mmd -f $mtmp 2>$null
                            if ($LASTEXITCODE -ne 0) { $art = $null }
                            Remove-Item $mtmp -ErrorAction SilentlyContinue
                        }
                        if ($art) {
                            [void]$out.AppendLine('```')
                            [void]$out.AppendLine(($art -join "`n"))
                            [void]$out.AppendLine('```')
                        } else {
                            [void]$out.AppendLine('```mermaid')
                            foreach ($b in $block) { [void]$out.AppendLine($b) }
                            [void]$out.AppendLine('```')
                        }
                        $block = $null
                        continue
                    }
                    $block += $line
                }
                if ($null -ne $block) {
                    [void]$out.AppendLine('```mermaid')
                    foreach ($b in $block) { [void]$out.AppendLine($b) }
                }
                $mermaidTmp = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName() + '.md')
                Set-Content -LiteralPath $mermaidTmp -Value $out.ToString() -Encoding utf8
                $doc = $mermaidTmp
            }

            $width = 100
            $cols = $Host.UI.RawUI.WindowSize.Width
            if ($cols -ge 40 -and $cols -lt $width) { $width = $cols }

            $glowArgs = @()
            if (Test-Path $conf) { $glowArgs += @('--config', $conf) }
            if (Test-Path $style) { $glowArgs += @('--style', $style) }
            $glowArgs += @('--width', $width)

            # less.exe — from PATH, else the copy Git for Windows bundles
            # (git is already a dependency, so this is expected to hit).
            $less = (Get-Command less -ErrorAction SilentlyContinue).Source
            if (-not $less) {
                $gitCmd = (Get-Command git -ErrorAction SilentlyContinue).Source
                $roots = @()
                if ($gitCmd) {
                    # ...\Git\cmd\git.exe or ...\Git\bin\git.exe -> ...\Git
                    $roots += (Split-Path (Split-Path $gitCmd -Parent) -Parent)
                }
                $roots += @($Env:ProgramFiles, ${Env:ProgramFiles(x86)}, $Env:LOCALAPPDATA) |
                    Where-Object { $_ } | ForEach-Object { Join-Path $_ 'Git' }
                foreach ($root in $roots) {
                    if (-not $root) { continue }
                    $cand = Join-Path $root 'usr\bin\less.exe'
                    if (Test-Path $cand) { $less = $cand; break }
                }
            }

            $oldPager = $Env:PAGER
            $oldLess = $Env:LESS
            $oldForce = $Env:CLICOLOR_FORCE
            try {
                $Env:CLICOLOR_FORCE = '1'
                if ($less) {
                    $Env:PAGER = $less
                    $Env:LESS = '--RAW-CONTROL-CHARS --mouse --quit-if-one-screen'
                    glow @glowArgs --pager $doc
                } else {
                    glow @glowArgs $doc
                }
            } finally {
                $Env:PAGER = $oldPager
                $Env:LESS = $oldLess
                $Env:CLICOLOR_FORCE = $oldForce
            }
        } finally {
            if ($tmp -and (Test-Path $tmp)) { Remove-Item $tmp -ErrorAction SilentlyContinue }
            if ($mermaidTmp -and (Test-Path $mermaidTmp)) { Remove-Item $mermaidTmp -ErrorAction SilentlyContinue }
        }
    }
}

function tools {
    $doc = Join-Path $HOME '.config\terminal-help.md'
    if (Test-Path $doc) {
        md-view $doc
    } else {
        Write-Host 'terminal-help.md not found - run hm_win in WSL to deploy it.'
    }
}

# --- Misc --------------------------------------------------------------
# uv installs tool shims (e.g. `vd` from visidata) into ~\.local\bin.
$uvBin = Join-Path $HOME '.local\bin'
if ((Test-Path $uvBin) -and ($Env:Path -notlike "*$uvBin*")) { $Env:Path += ";$uvBin" }

if (Get-Command nvim -ErrorAction SilentlyContinue) { $ENV:EDITOR = 'nvim' }
