# Native-Windows dotfiles, generated by Nix.
#
# There is no native Nix on Windows, so this does NOT manage Windows the
# way home-manager manages Linux. Instead it *generates* the Windows
# config artifacts (PowerShell profile, starship.toml, alacritty.toml,
# a psmux/tmux config, a Scoop install script, a winget configuration)
# from Nix, and ships a WSL-side command
# `hm_win` that copies them into the Windows user profile under
# /mnt/c/Users/<you>/. NTFS can't follow WSL symlinks, so we copy (with
# backups) rather than symlink.
#
# IMPORTANT — generation is gated behind `hm_win` only:
#   The generated artifacts are a separate flake package
#   (`packages.<system>.windows-dotfiles`). `hm_win` is a *thin* wrapper
#   that `nix build`s that package on demand and copies the result. So a
#   plain `home-manager switch` (i.e. `hm`/`nr`) installs only the small
#   wrapper and does NOT build or regenerate any Windows content — that
#   happens exclusively when you run `hm_win`.
#
# Workflow:
#   1. edit these files / the shared toolkit
#   2. hm_win        (builds windows-dotfiles from ~/nixos, pushes it)
#
# Contributes:
#   - flake.lib.starshipSettings — the prompt config, shared so the zsh
#     prompt (flake-modules/zsh.nix) and the PowerShell prompt are
#     identical from one definition.
#   - packages.<system>.windows-dotfiles — the generated bundle.
#   - flake.modules.homeManager.windows — installs the `hm_win` wrapper.
#     Imported by the WSL hosts only (it needs /mnt/c + Windows interop).
#
# Retire when: a native-Windows Nix/home-manager appears (unlikely), OR
#   the native-Windows environment is no longer wanted.
{ lib, config, ... }:
let
  # ── Shared prompt (also consumed by flake-modules/zsh.nix) ──────────
  starshipSettings = {
    add_newline = false;
    format = "$directory$git_branch$git_status$nix_shell$character";
    directory.truncation_length = 3;
    character = {
      success_symbol = "[>](bold green)";
      error_symbol = "[>](bold red)";
    };
  };

  # ── Shared atuin style (also consumed by flake-modules/zsh.nix) ─────
  # Just the cross-platform UI knobs: draw Ctrl-R inline (compact) rather
  # than repainting a full-screen TUI, so the picker pops instantly. The
  # `daemon` optimization is Unix-only (socket-activated systemd/launchd
  # unit) and is added on top by the home-manager atuin module in
  # zsh.nix, so it deliberately does NOT live here — Windows has no such
  # daemon and would break history recording if `daemon.enabled` were set
  # with nothing listening.
  atuinSettings = {
    style = "compact";
    inline_height = 12;
  };

  # ── Windows cursor theme (matches the Linux Bibata-Modern-Classic set
  # in flake-modules/desktop-extras.nix) ──────────────────────────────
  # Cursors aren't in winget/Scoop and the nixpkgs bibata-cursors package
  # ships X11 Xcursors, not Windows .cur/.ani — so setup.ps1 fetches the
  # official ful1e5/Bibata_Cursor Windows release. Pinned to a release tag
  # + the SHA-256 of the zip so the download is reproducible and
  # tamper-evident (same "pinned, verifiable source" bar as winget/Scoop).
  # Applied entirely user-scoped (HKCU\Control Panel\Cursors + files under
  # %LOCALAPPDATA%), so it needs no admin. `version` bumps + `sha256`
  # refresh together; get the hash from `Get-FileHash` or `sha256sum` of
  # Bibata-Modern-Classic-Windows.zip (uppercase hex).
  bibataCursor = {
    version = "v2.0.7";
    sha256 = "B98ECA4077D6E7796FF7E710E4D220CA13439F1118160D1E7B3DB9E91FDEC2BE";
  };

  # ── Mesa3D software OpenGL (for alacritty over RDP) ─────────────────
  # A Windows Remote Desktop session exposes no usable hardware OpenGL,
  # so alacritty (which needs a GL context) creates its window then exits
  # the event loop immediately — the classic RDP failure (alacritty#3865,
  # unfixable in alacritty). The fix is app-local software GL: drop Mesa's
  # llvmpipe opengl32.dll (+ libgallium_wgl.dll) next to alacritty.exe;
  # Windows loads the exe-dir opengl32.dll ahead of the system one, so
  # alacritty renders on the CPU and works over RDP. Mesa still
  # auto-selects the d3d12 hardware driver when a real GPU is present, so
  # it's not a downgrade on a local console. setup.ps1 only installs this
  # when it detects it is running inside an RDP session (Step 6), so
  # bare-metal/local boxes keep native GL untouched.
  #
  # Pinned to a mesa-dist-win release tag + the SHA-256 of the MSVC
  # release .7z (same "pinned, verifiable source" bar as the cursor and
  # winget/Scoop). `version` bumps + `sha256` refresh together; get the
  # hash from `Get-FileHash` / `sha256sum` of the .7z (uppercase hex).
  mesaGL = {
    version = "26.2.0";
    sha256 = "DCB2719EF346DAB5B609FCB193A5F13CFC4B0502E3F4DE1AD43D349477402F47";
  };

  # ── Package sources ─────────────────────────────────────────────────
  # Scoop is the DEFAULT for the CLI toolkit — most of these are single
  # self-contained binaries that corporate app-control doesn't flag.
  # winget is used only for (a) system apps, and (b) the few packages
  # that bundle extra *launcher* executables (e.g. git ships git-bash.exe
  # / pinentry.exe, uv ships uvw.exe) — those unsigned helper .exe's
  # under the user profile are what WDAC / AppLocker / Smart App Control
  # actually block (symptom: "'<tool>' isn't installed correctly"). For
  # those, winget's signed Program-Files install is the fix. winget IDs
  # verified against microsoft/winget-pkgs.

  # System apps via winget (7-Zip first — Scoop uses it as its extractor).
  wingetSystem = [
    { name = "7-Zip"; id = "7zip.7zip"; }
    { name = "PowerShell 7"; id = "Microsoft.PowerShell"; }
    { name = "Windows Terminal"; id = "Microsoft.WindowsTerminal"; }
    { name = "Azure CLI"; id = "Microsoft.AzureCLI"; }
  ];

  # CLI packages installed via winget. Most are here because their Scoop
  # builds bundle launcher/helper .exe's that app-control blocks; `gh` is
  # here by preference. `name` is the matching Scoop package, used by
  # setup.ps1 to remove a stale Scoop copy (e.g. an old scoop `gh`).
  wingetCli = [
    { name = "git"; id = "Git.Git"; } # git-bash.exe, pinentry.exe, …
    { name = "git-lfs"; id = "GitHub.GitLFS"; }
    { name = "uv"; id = "astral-sh.uv"; } # uvw.exe
    { name = "gh"; id = "GitHub.cli"; } # GitHub CLI — winget by preference
    # psmux — native-Windows, tmux-compatible terminal multiplexer (Rust,
    # ConPTY; no WSL/Cygwin). Installs the `psmux`, `pmux` and `tmux`
    # commands, and reads the generated ~/.psmux.conf deployed by hm_win.
    { name = "psmux"; id = "marlocarlo.psmux"; }
  ];

  # Everything else stays on Scoop (single binaries, not launcher shims).
  scoopApps = [
    "ripgrep"
    "fd"
    "fzf"
    "bat"
    "eza"
    "zoxide"
    "jq"
    "jaq"
    "yq"
    "gron"
    "dasel"
    "xh"
    "ouch"
    "delta"
    "difftastic"
    "lazygit"
    "glow"
    "tealdeer"
    "navi"
    "duckdb"
    "miller"
    "yazi"
    "vifm"
    "starship"
    "atuin"
    "ruff"
    "numbat"
    "sd"
    # GPU terminal, matching the Linux alacritty (config generated below
    # from the shared flake.lib.alacrittySettings). On Scoop (not winget)
    # deliberately: the RDP OpenGL fallback (Step 6 of setup.ps1) drops a
    # Mesa opengl32.dll next to alacritty.exe, and Scoop's per-user
    # apps\alacritty\current\ is writable without admin, unlike winget's
    # Program Files install. `extras` bucket (added by setup.ps1).
    "alacritty"
    # GNU coreutils, natively. uutils is a Rust reimplementation compiled
    # with MSVC — real Win32 binaries, no Cygwin/MSYS emulation layer and
    # no path translation. Gives head/tail/wc/cut/tr/uniq/seq/realpath/
    # sha256sum/… which PowerShell simply lacks, plus GNU semantics for
    # ls/cat/cp/mv/rm once profile.ps1 drops the shadowing PS aliases.
    # See the "GNU coreutils" block in profile.ps1 for the conflict list.
    #
    # Native-build safety: uutils also ships `link.exe` and `expand.exe`
    # shims, which would sit ahead of the MSVC linker and Windows' CAB
    # tool on PATH. setup.ps1 deletes both shims after every install
    # (Step 4), and profile.ps1 leaves the PowerShell aliases alone
    # inside a Visual Studio developer shell.
    "uutils-coreutils"
  ];

  # Nerd Font for the Windows-Terminal face "FantasqueSansM Nerd Font
  # Mono" (from the `nerd-fonts` Scoop bucket). The `-Mono` manifest
  # installs the single-cell-width family; the plain `FantasqueSansMono-NF`
  # manifest installs "FantasqueSansM Nerd Font" (non-Mono), whose patched
  # glyphs keep their original 1.5–2× advance and break the terminal grid
  # (overlapping/clipped letters) — same bug we hit on Linux/alacritty.
  scoopFonts = [ "FantasqueSansMono-NF-Mono" ];

  # Pure-Python tools with no winget/scoop package — installed via
  # `uv tool install` (uv itself comes from winget above). `vd` is the
  # visidata TUI; matches the Linux toolkit, which gets it from nixpkgs.
  # graphrag/graphifyy come from the shared `flake.lib.aiUvTools` list
  # (defined in flake-modules/ai-cli.nix) so Windows and the Linux
  # ai-cli bundle install the same AI tools from one definition. On
  # Linux those go through home-manager's uv activation; here they ride
  # setup.ps1's existing uv step.
  uvTools = [ "visidata" ] ++ config.flake.lib.aiUvTools;

  # Migration aid: winget IDs of CLI tools that an EARLIER version of this
  # setup installed via winget, but which now belong on Scoop. setup.ps1
  # uninstalls these from winget if present, so each tool ends up in a
  # single source (no duplicate binaries / PATH ambiguity). Safe to prune
  # once all machines have re-run setup.ps1. IDs verified against
  # microsoft/winget-pkgs.
  wingetRetired = [
    "BurntSushi.ripgrep.MSVC"
    "sharkdp.fd"
    "junegunn.fzf"
    "sharkdp.bat"
    "eza-community.eza"
    "ajeetdsouza.zoxide"
    "jqlang.jq"
    "MikeFarah.yq"
    "TomHudson.gron"
    "dandavison.delta"
    "Wilfred.difftastic"
    "JesseDuffield.lazygit"
    "charmbracelet.glow"
    "dbrgn.tealdeer"
    "DuckDB.cli"
    "Miller.Miller"
    "Neovim.Neovim"
    "Starship.Starship"
    "Atuinsh.Atuin"
    "astral-sh.ruff"
    "chmln.sd"
    # Moved winget -> Scoop so the RDP Mesa GL step can drop an app-local
    # opengl32.dll into a user-writable dir (Program Files would need
    # admin). setup.ps1 uninstalls the old winget copy.
    "Alacritty.Alacritty"
  ];

  # ── The generated bundle (built on demand by `hm_win`) ──────────────
  # Parameterized by pkgs so it works in perSystem for each build arch.
  mkWindowsDotfiles = pkgs:
    let
      starshipToml = (pkgs.formats.toml { }).generate "starship.toml" starshipSettings;
      atuinToml = (pkgs.formats.toml { }).generate "atuin-config.toml" atuinSettings;

      # alacritty.toml — generated from the SAME definition the Linux
      # alacritty module uses (flake.lib.alacrittySettings), so the
      # terminal is identical on both sides. One Windows-only override
      # baked in here: `window.decorations` forced back to "Full" (Linux
      # runs borderless under niri; on Windows there is no WM to move or
      # close a title-bar-less window).
      #
      # `terminal.shell` is deliberately NOT set here. We want alacritty
      # to start pwsh (PowerShell 7, matching profile.ps1) — but only
      # where it's installed. Baking `program = "pwsh"` statically breaks
      # every box without PowerShell 7: alacritty can't spawn the shell
      # and the window closes instantly (even with --hold, because a
      # failed spawn is not an exit). So hm_win appends the
      # [terminal.shell] table at DEPLOY time from its own pwsh/powershell
      # probe ($psexe), falling back to the always-present Windows
      # PowerShell 5.1 when pwsh is absent.
      # Deployed to %APPDATA%\alacritty\ by hm_win, which is where
      # alacritty looks on Windows.
      alacrittyToml = (pkgs.formats.toml { }).generate "alacritty.toml"
        (config.flake.lib.alacrittySettings // {
          window = config.flake.lib.alacrittySettings.window // {
            decorations = "Full";
          };
        });

      # psmux config — native-Windows, tmux-compatible multiplexer. The QOL
      # binds and the status bar are shared *verbatim* with Linux tmux via
      # flake.lib.tmuxPortableConfig (flake-modules/tmux.nix), so the two
      # can't drift — edit the bar/binds there, not here. Only three things
      # are psmux-specific and live below: the base settings (mouse, vi
      # copy-mode, 1-based indexing, scrollback, renumbering), the
      # colour-capability pin, and the reload path.
      #
      # Deliberately NOT shared from the Linux side (they need Unix terminfo
      # / are latency workarounds / use format conditionals psmux lacks):
      #   - `terminal tmux-256color` + `terminal-overrides …:Tc` (no terminfo
      #     on Windows — see the default-terminal note below instead)
      #   - `escape-time` (an X11/SSH ESC-latency workaround)
      #   - the `if-shell -F "#{alternate_on}" …` PageUp binding (Windows
      #     Terminal / alacritty already own scrollback, and format
      #     conditionals aren't in psmux's subset)
      psmuxConf = pkgs.writeText "psmux.conf" ''
        # Generated by the nixos flake (hm_win). The QOL binds + status bar
        # come from flake.lib.tmuxPortableConfig — edit tmux.nix, not here.
        set -g mouse on
        setw -g mode-keys vi
        set -g base-index 1
        setw -g pane-base-index 1
        set -g renumber-windows on
        set -g history-limit 100000

        # psmux already exports COLORTERM=truecolor and TERM=xterm-256color
        # to every pane, so apps inside it know we're 24-bit capable. Pin
        # TERM explicitly so no future default can silently downgrade it.
        # (Do NOT set tmux-256color here — Windows ships no terminfo for it,
        # which would leave child apps with a broken TERM.)
        set -g default-terminal "xterm-256color"

        ${config.flake.lib.tmuxPortableConfig}
        # Reload this config in place (prefix r).
        bind r source-file ~/.psmux.conf \; display "config reloaded"
      '';

      # Markdown rendering, shared with Linux. The style is defined once
      # in flake-modules/markdown-viewer.nix and published on
      # `flake.lib.markdownStyle`, so `md-view` looks identical in pwsh
      # and in zsh. See that module's header for why each glow setting is
      # pinned — the short version is that every built-in glamour theme
      # leaves the literal `##` markers on headings.
      mdViewStyle = (pkgs.formats.json { }).generate "md-view-style.json"
        config.flake.lib.markdownStyle;

      # An intentionally empty glow config. glow reads
      # ~/.config/glow/glow.yml (or the Windows equivalent) and a stray
      # `glow config` run there would otherwise change settings we don't
      # pass explicitly. On Linux this role is played by /dev/null, which
      # Windows has no usable equivalent of, so ship a real empty file.
      mdViewGlowConf = pkgs.writeText "md-view-glow.yml" "";

      # mermaid-ascii, cross-compiled to a native Windows .exe so the
      # PowerShell `md-view` can render ```mermaid blocks like the Linux
      # one does. Go cross-compiles cleanly, so this needs no Windows
      # toolchain — just GOOS/GOARCH. ~14 MiB, a single static binary
      # with no runtime dependency, which is the only reason it is worth
      # shipping through hm_win at all: the alternative (mermaid-cli)
      # would mean a Chromium install on Windows too.
      #
      # `env` rather than plain attrs: buildGoModule puts GOOS/GOARCH/
      # CGO_ENABLED in `env`, and setting them as derivation arguments
      # instead is a "cannot contain any attributes passed to derivation"
      # eval error.
      mermaidAsciiExe = pkgs.mermaid-ascii.overrideAttrs (o: {
        pname = "mermaid-ascii-windows";
        env = (o.env or { }) // {
          GOOS = "windows";
          GOARCH = "amd64";
          CGO_ENABLED = 0;
        };
      });



      setupScript = pkgs.writeText "setup.ps1" ''
        #Requires -Version 5.1
        # Generated by the nixos flake (hm_win). Reconciles native-Windows
        # packages toward the desired state. It snapshots what's already
        # installed ONCE per package manager, then acts only on the deltas
        # (install missing, uninstall retired) — brute-forcing a winget/
        # scoop call per package is slow because each does a source lookup.
        #
        #   - winget: system apps + the CLI packages whose Scoop builds
        #     bundle app-control-blocked launcher .exe's (git, git-lfs, uv).
        #   - uv: pure-Python tools (visidata) with no winget/scoop package.
        #   - Scoop: the rest of the CLI toolkit + a Nerd Font.
        #   - cleanup: drop duplicates so each tool has a single source.
        #   - cursor: Bibata-Modern-Classic (matches Linux), pinned+hashed
        #     GitHub release zip, applied user-scoped (no admin).
        #   - RDP GL: if running inside a Remote Desktop session, drop a
        #     Mesa software opengl32.dll next to alacritty.exe so alacritty
        #     runs over RDP (no hardware GL there). Skipped on a local
        #     console. Pinned+hashed, user-scoped (no admin).
        $ErrorActionPreference = 'Continue'  # keep going if one step fails

        # ---- Snapshot installed winget packages (one export call) --------
        $wingetIds = @{}
        if (Get-Command winget -ErrorAction SilentlyContinue) {
          $tmp = Join-Path $Env:TEMP 'winget-export.json'
          winget export -o $tmp --accept-source-agreements --disable-interactivity 2>$null | Out-Null
          if (Test-Path $tmp) {
            try {
              $data = Get-Content -Raw $tmp | ConvertFrom-Json
              foreach ($src in $data.Sources) {
                foreach ($pkg in $src.Packages) {
                  if ($pkg.PackageIdentifier) { $wingetIds[$pkg.PackageIdentifier] = $true }
                }
              }
            } catch { }
            Remove-Item $tmp -ErrorAction SilentlyContinue
          }
        }

        Write-Host '== Step 1/6: winget (system apps + git/git-lfs/uv) =='
        foreach ($id in @(${lib.concatMapStringsSep ", " (p: "'${p.id}'") (wingetSystem ++ wingetCli)})) {
          if ($wingetIds.ContainsKey($id)) {
            Write-Host "  ok (installed): $id"
          } else {
            Write-Host "  winget install $id"
            winget install --exact --id $id --accept-package-agreements --accept-source-agreements --disable-interactivity
          }
        }

        # Refresh PATH from the registry so tools winget just installed
        # (uv, 7-Zip, etc.) are visible in THIS session.
        $Env:Path = [Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
                    [Environment]::GetEnvironmentVariable('Path', 'User')

        Write-Host '== Step 2/6: uv (pure-Python tools) =='
        if (Get-Command uv -ErrorAction SilentlyContinue) {
          # Snapshot uv-installed tools once (top-level lines = tool names).
          $uvInstalled = @{}
          foreach ($line in (uv tool list 2>$null)) {
            if ($line -match '^(\S+)') { $uvInstalled[$matches[1]] = $true }
          }
          foreach ($t in @(${lib.concatMapStringsSep ", " (t: "'${t}'") uvTools})) {
            if ($uvInstalled.ContainsKey($t)) {
              Write-Host "  ok (installed): $t"
            } else {
              Write-Host "  uv tool install $t"
              uv tool install $t
            }
          }
          uv tool update-shell 2>$null
        } else {
          Write-Warning 'uv not found on PATH yet; skipping Python tools (vd). Restart the terminal and re-run setup.ps1.'
        }

        # Make the freshly-installed 7-Zip visible to Scoop's extractor.
        $sevenZipDir = Join-Path $Env:ProgramFiles '7-Zip'
        if (Test-Path (Join-Path $sevenZipDir '7z.exe')) {
          if ($Env:Path -notlike "*$sevenZipDir*") { $Env:Path += ";$sevenZipDir" }
        }

        Write-Host '== Step 3/6: Scoop (tools with no winget package) =='
        if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
          Write-Host 'Installing Scoop...'
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        }
        if (Test-Path (Join-Path $sevenZipDir '7z.exe')) {
          scoop config use_external_7zip $true | Out-Null
        }
        # Scoop install/uninstall state is just a folder under apps\, so
        # check the filesystem (fast) instead of calling `scoop list`.
        $scoopRoot = if ($Env:SCOOP) { $Env:SCOOP } else { Join-Path $HOME 'scoop' }
        function Test-ScoopApp([string]$app) { Test-Path (Join-Path $scoopRoot "apps\$app") }
        $bucketsAdded = $false
        foreach ($app in @(${lib.concatMapStringsSep ", " (a: "'${a}'") (scoopApps ++ scoopFonts)})) {
          if (Test-ScoopApp $app) {
            Write-Host "  ok (installed): $app"
          } else {
            if (-not $bucketsAdded) {
              foreach ($b in @('main', 'extras', 'nerd-fonts')) { scoop bucket add $b 2>$null }
              $bucketsAdded = $true
            }
            scoop install $app
          }
        }

        Write-Host '== Step 4/6: reconcile sources (one tool, one source) =='
        # Remove Scoop copies of the tools we moved to winget.
        foreach ($app in @(${lib.concatMapStringsSep ", " (p: "'${p.name}'") wingetCli})) {
          if (Test-ScoopApp $app) {
            Write-Host "  scoop uninstall $app (now provided by winget)"
            scoop uninstall $app
          }
        }
        # Remove winget copies of tools that now belong on Scoop (only the
        # ones the snapshot shows are actually installed via winget).
        foreach ($id in @(${lib.concatMapStringsSep ", " (i: "'${i}'") wingetRetired})) {
          if ($wingetIds.ContainsKey($id)) {
            Write-Host "  winget uninstall $id (now provided by Scoop)"
            winget uninstall --exact --id $id --silent --disable-interactivity 2>$null
          }
        }

        # uutils ships two shims whose names collide with native-build
        # tooling: `link.exe` (the Visual C++ linker) and `expand.exe`
        # (Windows' CAB extractor). scoop\shims sits early on PATH, so
        # leaving them in place risks a VC build resolving GNU link(1)
        # instead of the linker. Neither GNU tool earns that risk — `ln`
        # already covers link(1), and expand(1) (tabs → spaces) is
        # trivially replaceable. Pruned after every run because scoop
        # recreates shims on install and on update.
        $shimDir = Join-Path $scoopRoot 'shims'
        foreach ($shim in 'link', 'expand') {
          Get-ChildItem -Path $shimDir -Filter "$shim.*" -ErrorAction SilentlyContinue |
            Where-Object { $_.BaseName -eq $shim } |
            ForEach-Object {
              Write-Host "  removing shim $($_.Name) (collides with the MSVC toolchain)"
              Remove-Item $_.FullName -Force
            }
        }

        Write-Host '== Step 5/6: cursor theme (Bibata-Modern-Classic) =='
        # Matches the Linux Bibata-Modern-Classic set. Pinned+hashed
        # official release zip; applied user-scoped (HKCU + %LOCALAPPDATA%),
        # so no admin. The nixpkgs package is X11-only, hence the download.
        $curScheme  = 'Bibata-Modern-Classic'
        $curVersion = '${bibataCursor.version}'
        $curSha256  = '${bibataCursor.sha256}'
        $curRoot    = Join-Path $Env:LOCALAPPDATA "cursors\$curScheme"
        $curMarker  = Join-Path $curRoot '.installed-version'
        if ((Test-Path $curMarker) -and ((Get-Content -Raw $curMarker).Trim() -eq $curVersion)) {
          Write-Host "  ok (installed): $curScheme $curVersion"
        } else {
          try {
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            $curUrl = "https://github.com/ful1e5/Bibata_Cursor/releases/download/$curVersion/Bibata-Modern-Classic-Windows.zip"
            $curZip = Join-Path $Env:TEMP "bibata-$curVersion.zip"
            Write-Host "  downloading $curUrl"
            Invoke-WebRequest -Uri $curUrl -OutFile $curZip -UseBasicParsing
            $curGot = (Get-FileHash -Algorithm SHA256 -Path $curZip).Hash
            if ($curGot -ne $curSha256) {
              Write-Warning "  cursor zip SHA256 mismatch (got $curGot) - skipping cursor install"
            } else {
              $curTmp = Join-Path $Env:TEMP "bibata-$curVersion"
              if (Test-Path $curTmp) { Remove-Item -Recurse -Force $curTmp }
              Expand-Archive -Path $curZip -DestinationPath $curTmp -Force
              $curSrc = Join-Path $curTmp 'Bibata-Modern-Classic-Regular-Windows'
              if (Test-Path $curRoot) { Remove-Item -Recurse -Force $curRoot }
              New-Item -ItemType Directory -Force -Path $curRoot | Out-Null
              Copy-Item -Path (Join-Path $curSrc '*') -Destination $curRoot -Recurse -Force
              # Windows cursor role -> Bibata file (from the zip's install.inf [Wreg]).
              $curMap = @{}
              $curMap['Arrow']       = 'Pointer.cur'
              $curMap['Help']        = 'Help.cur'
              $curMap['AppStarting'] = 'Work.ani'
              $curMap['Wait']        = 'Busy.ani'
              $curMap['Crosshair']   = 'Cross.cur'
              $curMap['IBeam']       = 'Text.cur'
              $curMap['NWPen']       = 'Handwriting.cur'
              $curMap['No']          = 'Unavailable.cur'
              $curMap['SizeNS']      = 'Vert.cur'
              $curMap['SizeWE']      = 'Horz.cur'
              $curMap['SizeNWSE']    = 'Dgn1.cur'
              $curMap['SizeNESW']    = 'Dgn2.cur'
              $curMap['SizeAll']     = 'Move.cur'
              $curMap['UpArrow']     = 'Alternate.cur'
              $curMap['Hand']        = 'Link.cur'
              $curReg = 'HKCU:\Control Panel\Cursors'
              Set-ItemProperty -Path $curReg -Name '(default)' -Value "$curScheme-Regular Cursors"
              foreach ($role in $curMap.Keys) {
                Set-ItemProperty -Path $curReg -Name $role -Value (Join-Path $curRoot $curMap[$role])
              }
              Set-Content -Path $curMarker -Value $curVersion
              # Apply immediately (SPI_SETCURSORS = 0x0057) so no logoff is needed.
              if (-not ('Win32.NativeCursor' -as [type])) {
                Add-Type -Namespace Win32 -Name NativeCursor -MemberDefinition '[System.Runtime.InteropServices.DllImport("user32.dll", SetLastError=true)] public static extern bool SystemParametersInfo(uint a, uint b, System.IntPtr c, uint d);'
              }
              [void][Win32.NativeCursor]::SystemParametersInfo(0x0057, 0, [IntPtr]::Zero, 3)
              Write-Host "  installed + applied: $curScheme $curVersion"
            }
            Remove-Item $curZip -ErrorAction SilentlyContinue
          } catch {
            Write-Warning "  cursor install failed: $($_.Exception.Message)"
          }
        }

        Write-Host '== Step 6/6: OpenGL software fallback for RDP (Mesa) =='
        # Only over Remote Desktop: RDP exposes no hardware OpenGL, so
        # alacritty can't create its GL context and exits the event loop
        # immediately (alacritty#3865). An app-local Mesa opengl32.dll
        # (llvmpipe) next to alacritty.exe fixes it — Windows loads the
        # exe-dir DLL ahead of the system one. Mesa still auto-selects the
        # d3d12 hardware driver when a real GPU is present, so it's safe to
        # leave in place. Skipped on a local console so native GL is
        # untouched. User-scoped (Scoop's apps dir), no admin.
        if (-not ('Win32.RdpCheck' -as [type])) {
          Add-Type -Namespace Win32 -Name RdpCheck -MemberDefinition '[System.Runtime.InteropServices.DllImport("user32.dll")] public static extern int GetSystemMetrics(int n);'
        }
        # SM_REMOTESESSION = 0x1000: non-zero when the session is remote.
        $isRdp = $false
        try { $isRdp = ([Win32.RdpCheck]::GetSystemMetrics(0x1000) -ne 0) } catch { }
        if ((-not $isRdp) -and $Env:SESSIONNAME) { $isRdp = ($Env:SESSIONNAME -like 'RDP-*') }

        if (-not $isRdp) {
          Write-Host '  local console (not RDP); leaving native OpenGL in place'
        } else {
          $alacrittyDir = Join-Path $scoopRoot 'apps\alacritty\current'
          $sevenZipExe = Join-Path $sevenZipDir '7z.exe'
          if (-not (Test-Path (Join-Path $alacrittyDir 'alacritty.exe'))) {
            Write-Host '  alacritty (scoop) not installed yet; skipping Mesa GL. Re-run setup.ps1 after it installs.'
          } elseif (-not (Test-Path $sevenZipExe)) {
            Write-Warning '  7-Zip not found; cannot extract Mesa. Skipping.'
          } else {
            $mesaVersion = '${mesaGL.version}'
            $mesaSha256 = '${mesaGL.sha256}'
            $mesaMarker = Join-Path $alacrittyDir '.mesa-gl-version'
            if ((Test-Path $mesaMarker) -and ((Get-Content -Raw $mesaMarker).Trim() -eq $mesaVersion) -and
                (Test-Path (Join-Path $alacrittyDir 'opengl32.dll'))) {
              Write-Host "  ok (installed): Mesa $mesaVersion software GL"
            } else {
              try {
                [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
                $mesaUrl = "https://github.com/pal1000/mesa-dist-win/releases/download/$mesaVersion/mesa3d-$mesaVersion-release-msvc.7z"
                $mesa7z = Join-Path $Env:TEMP "mesa-$mesaVersion.7z"
                Write-Host "  downloading $mesaUrl"
                Invoke-WebRequest -Uri $mesaUrl -OutFile $mesa7z -UseBasicParsing
                $mesaGot = (Get-FileHash -Algorithm SHA256 -Path $mesa7z).Hash
                if ($mesaGot -ne $mesaSha256) {
                  Write-Warning "  Mesa .7z SHA256 mismatch (got $mesaGot) - skipping"
                } else {
                  $mesaTmp = Join-Path $Env:TEMP "mesa-$mesaVersion"
                  if (Test-Path $mesaTmp) { Remove-Item -Recurse -Force $mesaTmp }
                  # llvmpipe needs opengl32.dll + libgallium_wgl.dll; dxil.dll
                  # lets Mesa also drive the d3d12 hardware path on a real GPU.
                  & $sevenZipExe x $mesa7z 'x64/opengl32.dll' 'x64/libgallium_wgl.dll' 'x64/dxil.dll' "-o$mesaTmp" -y | Out-Null
                  foreach ($dll in 'opengl32.dll', 'libgallium_wgl.dll', 'dxil.dll') {
                    $from = Join-Path $mesaTmp "x64\$dll"
                    if (Test-Path $from) {
                      Copy-Item -Path $from -Destination (Join-Path $alacrittyDir $dll) -Force
                    }
                  }
                  Set-Content -Path $mesaMarker -Value $mesaVersion
                  Remove-Item -Recurse -Force $mesaTmp -ErrorAction SilentlyContinue
                  Write-Host "  installed: Mesa $mesaVersion software GL next to alacritty.exe"
                }
                Remove-Item $mesa7z -ErrorAction SilentlyContinue
              } catch {
                Write-Warning "  Mesa GL install failed: $($_.Exception.Message)"
              }
            }
          }
        }

        Write-Host
        Write-Host 'Done. Restart your terminal.'
      '';
    in
    pkgs.runCommand "windows-dotfiles" { } ''
      mkdir -p "$out"
      cp ${./profile.ps1}        "$out/profile.ps1"
      cp ${starshipToml}         "$out/starship.toml"
      cp ${atuinToml}            "$out/atuin-config.toml"
      cp ${alacrittyToml}        "$out/alacritty.toml"
      cp ${psmuxConf}            "$out/psmux.conf"
      cp ${../terminal-help.md}  "$out/terminal-help.md"
      cp ${mdViewStyle}          "$out/md-view-style.json"
      cp ${mdViewGlowConf}       "$out/md-view-glow.yml"
      cp ${mermaidAsciiExe}/bin/windows_amd64/mermaid-ascii.exe "$out/mermaid-ascii.exe"
      cp ${setupScript}          "$out/setup.ps1"
    '';

  # ── `hm_win`: thin wrapper — builds the bundle, then deploys it ─────
  # Deliberately carries NO reference to the generated files, so its
  # closure (and therefore `home-manager switch`) stays tiny; the bundle
  # is built only when this runs.
  mkHmWin = pkgs: pkgs.writeShellApplication {
    name = "hm_win";
    runtimeInputs = [ pkgs.coreutils pkgs.jq ];
    # SC2016: we deliberately pass single-quoted *PowerShell* expressions
    # (e.g. '$PROFILE') to pwsh.exe — they must NOT be expanded by bash.
    excludeShellChecks = [ "SC2016" ];
    text = ''
      if ! command -v wslpath >/dev/null 2>&1; then
        echo "hm_win: must be run inside WSL (wslpath not found)." >&2
        exit 1
      fi

      # --setup / -s: after deploying, also run setup.ps1 on Windows
      # (winget + Scoop installs). Off by default — deploying dotfiles is
      # fast and frequent; the installs are slow and idempotent, so you
      # only want them when the package list actually changed.
      run_setup=0
      for arg in "$@"; do
        case "$arg" in
          -s | --setup) run_setup=1 ;;
          -h | --help)
            echo "usage: hm_win [--setup]"
            echo "  (no args)   deploy the Nix-generated dotfiles to the Windows profile"
            echo "  --setup,-s  also run setup.ps1 (winget + Scoop installs) afterwards"
            exit 0
            ;;
          *)
            echo "hm_win: unknown argument: $arg (try --help)" >&2
            exit 2
            ;;
        esac
      done

      # Build the generated bundle on demand from the local checkout
      # (override with HM_WIN_FLAKE). Nothing here is pre-built by
      # home-manager switch.
      flake="''${HM_WIN_FLAKE:-$HOME/nixos}"
      echo "hm_win: building windows-dotfiles from $flake ..."
      src="$(nix build "$flake#windows-dotfiles" --no-link --print-out-paths | tail -1)"
      if [ -z "$src" ] || [ ! -d "$src" ]; then
        echo "hm_win: failed to build windows-dotfiles." >&2
        exit 1
      fi

      # Detect the Windows profile at RUNTIME via the Windows interop.
      # This is a normal shell query on your machine (NOT Nix eval), so
      # it needs no `--impure` and adapts to the real account name and an
      # OneDrive-redirected Documents folder. powershell.exe (5.1) always
      # exists; prefer pwsh.exe (7) if installed.
      psexe=""
      for c in pwsh.exe powershell.exe; do
        if command -v "$c" >/dev/null 2>&1; then psexe="$c"; break; fi
      done
      userprofile_win=""
      profile_win=""
      if [ -n "$psexe" ]; then
        userprofile_win="$("$psexe" -NoProfile -NonInteractive -Command '[Environment]::GetFolderPath("UserProfile")' 2>/dev/null | tr -d '\r\n')"
        profile_win="$("$psexe" -NoProfile -NonInteractive -Command '$PROFILE.CurrentUserAllHosts' 2>/dev/null | tr -d '\r\n')"
      fi
      if [ -z "''${userprofile_win}" ]; then
        userprofile_win="$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r\n')"
      fi

      if [ -n "''${userprofile_win}" ]; then
        userprofile="$(wslpath -u "$userprofile_win")"
      elif [ -n "''${HM_WIN_USER:-}" ]; then
        # Interop unavailable but the user told us the account name.
        userprofile="$(wslpath -u "C:/Users/$HM_WIN_USER" 2>/dev/null || true)"
        if [ -z "$userprofile" ] || [ ! -d "$userprofile" ]; then
          userprofile="/mnt/c/Users/$HM_WIN_USER"
        fi
      else
        echo "hm_win: couldn't detect the Windows profile via the interop." >&2
        echo "       Set HM_WIN_USER=<your-windows-username> and re-run." >&2
        exit 1
      fi

      # PowerShell profile path: the real $PROFILE (handles OneDrive)
      # when interop is available, else the default Documents location.
      if [ -n "''${profile_win}" ]; then
        profile_path="$(wslpath -u "$profile_win")"
      else
        profile_path="$userprofile/Documents/PowerShell/profile.ps1"
      fi

      cfg="$userprofile/.config"
      nixwin="$cfg/nixwin"

      backup() {
        if [ -e "$1" ] && [ ! -L "$1" ]; then
          cp -f "$1" "$1.bak.$(date +%Y%m%d%H%M%S)"
          echo "  backed up: $1"
        fi
      }
      deploy() {
        mkdir -p "$(dirname "$2")"
        backup "$2"
        install -m 0644 "$1" "$2"
        echo "  deployed: $2"
      }

      echo "hm_win: deploying to $userprofile"
      deploy "$src/profile.ps1" "$profile_path"
      deploy "$src/starship.toml" "$cfg/starship.toml"
      # atuin reads %APPDATA%\atuin by default on Windows, NOT ~/.config;
      # profile.ps1 sets ATUIN_CONFIG_DIR to this path so it picks up the
      # Nix-generated config (compact/inline style, matching the WSL/zsh
      # setup) instead of atuin's own default.
      deploy "$src/atuin-config.toml" "$cfg/atuin/config.toml"
      # alacritty reads %APPDATA%\alacritty\alacritty.toml on Windows
      # (NOT ~/.config), so deploy there directly.
      alacritty_toml="$userprofile/AppData/Roaming/alacritty/alacritty.toml"
      deploy "$src/alacritty.toml" "$alacritty_toml"
      # Pick alacritty's shell at deploy time, NOT in the Nix-generated
      # file: start pwsh (PowerShell 7, matching profile.ps1) where it's
      # installed, else fall back to the always-present Windows PowerShell
      # 5.1. A statically-baked `program = "pwsh"` makes alacritty fail to
      # launch on any box without pwsh — the spawn fails and the window
      # closes instantly (even with --hold). $psexe is the same probe used
      # for the rest of hm_win; strip the .exe for alacritty's program.
      alacritty_shell="powershell"
      if [ -n "$psexe" ]; then alacritty_shell="''${psexe%.exe}"; fi
      {
        echo ""
        echo "[terminal.shell]"
        echo "program = \"$alacritty_shell\""
      } >> "$alacritty_toml"
      echo "  alacritty shell: $alacritty_shell"
      # psmux (native-Windows tmux) reads ~/.psmux.conf from the Windows
      # home directory.
      deploy "$src/psmux.conf" "$userprofile/.psmux.conf"
      deploy "$src/terminal-help.md" "$cfg/terminal-help.md"
      # Markdown rendering config for the `md-view` / `tools` functions in
      # profile.ps1 — the same glamour style the Linux md-view uses.
      deploy "$src/md-view-style.json" "$nixwin/md-view-style.json"
      deploy "$src/md-view-glow.yml" "$nixwin/md-view-glow.yml"
      # The only binary hm_win ships. 0755 because deploy() installs
      # 0644, which would leave it non-executable under WSL — Windows
      # itself ignores the mode, but running it from WSL for testing
      # would fail confusingly.
      deploy "$src/mermaid-ascii.exe" "$nixwin/bin/mermaid-ascii.exe"
      chmod 0755 "$nixwin/bin/mermaid-ascii.exe"
      deploy "$src/setup.ps1" "$nixwin/setup.ps1"

      # Windows Terminal: set only the default font face/size, merged
      # into the existing settings.json with jq (non-destructive re: other
      # keys). Face and size are force-set (not `// default`) so a size
      # bump here actually lands on machines that already ran hm_win.
      # Keybindings are intentionally left at their defaults.
      shopt -s nullglob
      wt_found=0
      for s in "$userprofile"/AppData/Local/Packages/Microsoft.WindowsTerminal_*/LocalState/settings.json; do
        wt_found=1
        backup "$s"
        tmp="$(mktemp)"
        if jq '.profiles.defaults.font.face = "FantasqueSansM Nerd Font Mono"
               | .profiles.defaults.font.size = 13' \
             "$s" > "$tmp" 2>/dev/null; then
          mv "$tmp" "$s"
          echo "  Windows Terminal font set: $s"
        else
          rm -f "$tmp"
          echo "  WARN: could not update $s (left unchanged)"
        fi
      done
      shopt -u nullglob
      if [ "$wt_found" -eq 0 ]; then
        echo "  (Windows Terminal settings.json not found; skipped font)"
      fi

      # Ensure uv's tool-bin dir is on the Windows PATH, so executables
      # from `uv tool install` resolve in new shells. setup.ps1 already
      # does this, but only under --setup; run it here too so a plain
      # deploy (the `nh win switch` path) keeps PATH current. Best-effort:
      # needs the Windows interop + uv (from winget) — a box without uv
      # yet simply skips.
      if [ -n "$psexe" ]; then
        echo "hm_win: uv tool update-shell (Windows PATH)"
        "$psexe" -NoProfile -NonInteractive -Command \
          'if (Get-Command uv -ErrorAction SilentlyContinue) { uv tool update-shell }' \
          2>/dev/null || true
      fi

      setup_win="$(wslpath -w "$nixwin/setup.ps1")"
      if [ "$run_setup" -eq 1 ]; then
        if [ -z "$psexe" ]; then
          echo "hm_win: --setup needs the Windows PowerShell interop, which wasn't found." >&2
          echo "       Run this manually in PowerShell: $setup_win" >&2
          exit 1
        fi
        echo ""
        echo "hm_win: running setup.ps1 on Windows ($psexe) ..."
        # -ExecutionPolicy Bypass: the generated script is unsigned.
        "$psexe" -NoProfile -ExecutionPolicy Bypass -File "$setup_win"
        echo ""
        echo "Done. Restart your terminal to pick up everything."
      else
        echo ""
        echo "Done deploying. To install/update the toolkit, either:"
        echo "  hm_win --setup            # run the installer from here, or"
        echo "  $setup_win   # run it yourself in PowerShell"
        echo "(winget + Scoop installs). Then restart your terminal."
      fi
    '';
  };
in
{
  flake.lib.starshipSettings = starshipSettings;
  flake.lib.atuinSettings = atuinSettings;

  flake.modules.homeManager.windows = { pkgs, ... }: {
    home.packages = [ (mkHmWin pkgs) ];
  };

  # `config.flake.lib.mkPkgs system` rather than perSystem's own `pkgs`:
  # flake-parts hands out a bare nixpkgs, without this repo's overlays,
  # and the bundle needs one of them (mermaid-ascii, for the cross
  # -compiled .exe). Same factory every host bridge uses, so the Windows
  # bundle is built from exactly the same package set as everything else.
  perSystem = { system, ... }: {
    packages.windows-dotfiles = mkWindowsDotfiles (config.flake.lib.mkPkgs system);
  };
}
