# Native-Windows dotfiles, generated by Nix.
#
# There is no native Nix on Windows, so this does NOT manage Windows the
# way home-manager manages Linux. Instead it *generates* the Windows
# config artifacts (PowerShell profile, starship.toml, a Scoop install
# script, a winget configuration) from Nix, and ships a WSL-side command
# `hm_win` that copies them into the Windows user profile under
# /mnt/c/Users/<you>/. NTFS can't follow WSL symlinks, so we copy (with
# backups) rather than symlink.
#
# IMPORTANT — generation is gated behind `hm_win` only:
#   The generated artifacts are a separate flake package
#   (`packages.<system>.windows-dotfiles`). `hm_win` is a *thin* wrapper
#   that `nix build`s that package on demand and copies the result. So a
#   plain `home-manager switch` (i.e. `hm`/`nr`) installs only the small
#   wrapper and does NOT build or regenerate any Windows content — that
#   happens exclusively when you run `hm_win`.
#
# Workflow:
#   1. edit these files / the shared toolkit
#   2. hm_win        (builds windows-dotfiles from ~/nixos, pushes it)
#
# Contributes:
#   - flake.lib.starshipSettings — the prompt config, shared so the zsh
#     prompt (flake-modules/zsh.nix) and the PowerShell prompt are
#     identical from one definition.
#   - packages.<system>.windows-dotfiles — the generated bundle.
#   - flake.modules.homeManager.windows — installs the `hm_win` wrapper.
#     Imported by the WSL hosts only (it needs /mnt/c + Windows interop).
#
# Retire when: a native-Windows Nix/home-manager appears (unlikely), OR
#   the native-Windows environment is no longer wanted.
{ lib, config, ... }:
let
  # ── Shared prompt (also consumed by flake-modules/zsh.nix) ──────────
  starshipSettings = {
    add_newline = false;
    format = "$directory$git_branch$git_status$nix_shell$character";
    directory.truncation_length = 3;
    character = {
      success_symbol = "[>](bold green)";
      error_symbol = "[>](bold red)";
    };
  };

  # ── Package sources ─────────────────────────────────────────────────
  # Scoop is the DEFAULT for the CLI toolkit — most of these are single
  # self-contained binaries that corporate app-control doesn't flag.
  # winget is used only for (a) system apps, and (b) the few packages
  # that bundle extra *launcher* executables (e.g. git ships git-bash.exe
  # / pinentry.exe, uv ships uvw.exe) — those unsigned helper .exe's
  # under the user profile are what WDAC / AppLocker / Smart App Control
  # actually block (symptom: "'<tool>' isn't installed correctly"). For
  # those, winget's signed Program-Files install is the fix. winget IDs
  # verified against microsoft/winget-pkgs.

  # System apps via winget (7-Zip first — Scoop uses it as its extractor).
  wingetSystem = [
    { name = "7-Zip"; id = "7zip.7zip"; }
    { name = "PowerShell 7"; id = "Microsoft.PowerShell"; }
    { name = "Windows Terminal"; id = "Microsoft.WindowsTerminal"; }
    { name = "Azure CLI"; id = "Microsoft.AzureCLI"; }
  ];

  # CLI packages installed via winget. Most are here because their Scoop
  # builds bundle launcher/helper .exe's that app-control blocks; `gh` is
  # here by preference. `name` is the matching Scoop package, used by
  # setup.ps1 to remove a stale Scoop copy (e.g. an old scoop `gh`).
  wingetCli = [
    { name = "git"; id = "Git.Git"; } # git-bash.exe, pinentry.exe, …
    { name = "git-lfs"; id = "GitHub.GitLFS"; }
    { name = "uv"; id = "astral-sh.uv"; } # uvw.exe
    { name = "gh"; id = "GitHub.cli"; } # GitHub CLI — winget by preference
  ];

  # Everything else stays on Scoop (single binaries, not launcher shims).
  scoopApps = [
    "ripgrep"
    "fd"
    "fzf"
    "bat"
    "eza"
    "zoxide"
    "jq"
    "jaq"
    "yq"
    "gron"
    "dasel"
    "xh"
    "ouch"
    "delta"
    "difftastic"
    "lazygit"
    "glow"
    "tealdeer"
    "navi"
    "duckdb"
    "miller"
    "yazi"
    "vifm"
    "starship"
    "atuin"
    "ruff"
    "numbat"
    "sd"
  ];

  # Nerd Font for the Windows-Terminal face "FantasqueSansM Nerd Font
  # Mono" (from the `nerd-fonts` Scoop bucket). The `-Mono` manifest
  # installs the single-cell-width family; the plain `FantasqueSansMono-NF`
  # manifest installs "FantasqueSansM Nerd Font" (non-Mono), whose patched
  # glyphs keep their original 1.5–2× advance and break the terminal grid
  # (overlapping/clipped letters) — same bug we hit on Linux/alacritty.
  scoopFonts = [ "FantasqueSansMono-NF-Mono" ];

  # Pure-Python tools with no winget/scoop package — installed via
  # `uv tool install` (uv itself comes from winget above). `vd` is the
  # visidata TUI; matches the Linux toolkit, which gets it from nixpkgs.
  # graphrag/graphifyy come from the shared `flake.lib.aiUvTools` list
  # (defined in flake-modules/ai-cli.nix) so Windows and the Linux
  # ai-cli bundle install the same AI tools from one definition. On
  # Linux those go through home-manager's uv activation; here they ride
  # setup.ps1's existing uv step.
  uvTools = [ "visidata" ] ++ config.flake.lib.aiUvTools;

  # Migration aid: winget IDs of CLI tools that an EARLIER version of this
  # setup installed via winget, but which now belong on Scoop. setup.ps1
  # uninstalls these from winget if present, so each tool ends up in a
  # single source (no duplicate binaries / PATH ambiguity). Safe to prune
  # once all machines have re-run setup.ps1. IDs verified against
  # microsoft/winget-pkgs.
  wingetRetired = [
    "BurntSushi.ripgrep.MSVC"
    "sharkdp.fd"
    "junegunn.fzf"
    "sharkdp.bat"
    "eza-community.eza"
    "ajeetdsouza.zoxide"
    "jqlang.jq"
    "MikeFarah.yq"
    "TomHudson.gron"
    "dandavison.delta"
    "Wilfred.difftastic"
    "JesseDuffield.lazygit"
    "charmbracelet.glow"
    "dbrgn.tealdeer"
    "DuckDB.cli"
    "Miller.Miller"
    "Neovim.Neovim"
    "Starship.Starship"
    "Atuinsh.Atuin"
    "astral-sh.ruff"
    "chmln.sd"
  ];

  # ── The generated bundle (built on demand by `hm_win`) ──────────────
  # Parameterized by pkgs so it works in perSystem for each build arch.
  mkWindowsDotfiles = pkgs:
    let
      starshipToml = (pkgs.formats.toml { }).generate "starship.toml" starshipSettings;

      setupScript = pkgs.writeText "setup.ps1" ''
        #Requires -Version 5.1
        # Generated by the nixos flake (hm_win). Reconciles native-Windows
        # packages toward the desired state. It snapshots what's already
        # installed ONCE per package manager, then acts only on the deltas
        # (install missing, uninstall retired) — brute-forcing a winget/
        # scoop call per package is slow because each does a source lookup.
        #
        #   - winget: system apps + the CLI packages whose Scoop builds
        #     bundle app-control-blocked launcher .exe's (git, git-lfs, uv).
        #   - uv: pure-Python tools (visidata) with no winget/scoop package.
        #   - Scoop: the rest of the CLI toolkit + a Nerd Font.
        #   - cleanup: drop duplicates so each tool has a single source.
        $ErrorActionPreference = 'Continue'  # keep going if one step fails

        # ---- Snapshot installed winget packages (one export call) --------
        $wingetIds = @{}
        if (Get-Command winget -ErrorAction SilentlyContinue) {
          $tmp = Join-Path $Env:TEMP 'winget-export.json'
          winget export -o $tmp --accept-source-agreements --disable-interactivity 2>$null | Out-Null
          if (Test-Path $tmp) {
            try {
              $data = Get-Content -Raw $tmp | ConvertFrom-Json
              foreach ($src in $data.Sources) {
                foreach ($pkg in $src.Packages) {
                  if ($pkg.PackageIdentifier) { $wingetIds[$pkg.PackageIdentifier] = $true }
                }
              }
            } catch { }
            Remove-Item $tmp -ErrorAction SilentlyContinue
          }
        }

        Write-Host '== Step 1/4: winget (system apps + git/git-lfs/uv) =='
        foreach ($id in @(${lib.concatMapStringsSep ", " (p: "'${p.id}'") (wingetSystem ++ wingetCli)})) {
          if ($wingetIds.ContainsKey($id)) {
            Write-Host "  ok (installed): $id"
          } else {
            Write-Host "  winget install $id"
            winget install --exact --id $id --accept-package-agreements --accept-source-agreements --disable-interactivity
          }
        }

        # Refresh PATH from the registry so tools winget just installed
        # (uv, 7-Zip, etc.) are visible in THIS session.
        $Env:Path = [Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
                    [Environment]::GetEnvironmentVariable('Path', 'User')

        Write-Host '== Step 2/4: uv (pure-Python tools) =='
        if (Get-Command uv -ErrorAction SilentlyContinue) {
          # Snapshot uv-installed tools once (top-level lines = tool names).
          $uvInstalled = @{}
          foreach ($line in (uv tool list 2>$null)) {
            if ($line -match '^(\S+)') { $uvInstalled[$matches[1]] = $true }
          }
          foreach ($t in @(${lib.concatMapStringsSep ", " (t: "'${t}'") uvTools})) {
            if ($uvInstalled.ContainsKey($t)) {
              Write-Host "  ok (installed): $t"
            } else {
              Write-Host "  uv tool install $t"
              uv tool install $t
            }
          }
          uv tool update-shell 2>$null
        } else {
          Write-Warning 'uv not found on PATH yet; skipping Python tools (vd). Restart the terminal and re-run setup.ps1.'
        }

        # Make the freshly-installed 7-Zip visible to Scoop's extractor.
        $sevenZipDir = Join-Path $Env:ProgramFiles '7-Zip'
        if (Test-Path (Join-Path $sevenZipDir '7z.exe')) {
          if ($Env:Path -notlike "*$sevenZipDir*") { $Env:Path += ";$sevenZipDir" }
        }

        Write-Host '== Step 3/4: Scoop (tools with no winget package) =='
        if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
          Write-Host 'Installing Scoop...'
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        }
        if (Test-Path (Join-Path $sevenZipDir '7z.exe')) {
          scoop config use_external_7zip $true | Out-Null
        }
        # Scoop install/uninstall state is just a folder under apps\, so
        # check the filesystem (fast) instead of calling `scoop list`.
        $scoopRoot = if ($Env:SCOOP) { $Env:SCOOP } else { Join-Path $HOME 'scoop' }
        function Test-ScoopApp([string]$app) { Test-Path (Join-Path $scoopRoot "apps\$app") }
        $bucketsAdded = $false
        foreach ($app in @(${lib.concatMapStringsSep ", " (a: "'${a}'") (scoopApps ++ scoopFonts)})) {
          if (Test-ScoopApp $app) {
            Write-Host "  ok (installed): $app"
          } else {
            if (-not $bucketsAdded) {
              foreach ($b in @('main', 'extras', 'nerd-fonts')) { scoop bucket add $b 2>$null }
              $bucketsAdded = $true
            }
            scoop install $app
          }
        }

        Write-Host '== Step 4/4: reconcile sources (one tool, one source) =='
        # Remove Scoop copies of the tools we moved to winget.
        foreach ($app in @(${lib.concatMapStringsSep ", " (p: "'${p.name}'") wingetCli})) {
          if (Test-ScoopApp $app) {
            Write-Host "  scoop uninstall $app (now provided by winget)"
            scoop uninstall $app
          }
        }
        # Remove winget copies of tools that now belong on Scoop (only the
        # ones the snapshot shows are actually installed via winget).
        foreach ($id in @(${lib.concatMapStringsSep ", " (i: "'${i}'") wingetRetired})) {
          if ($wingetIds.ContainsKey($id)) {
            Write-Host "  winget uninstall $id (now provided by Scoop)"
            winget uninstall --exact --id $id --silent --disable-interactivity 2>$null
          }
        }

        Write-Host
        Write-Host 'Done. Restart your terminal.'
      '';
    in
    pkgs.runCommand "windows-dotfiles" { } ''
      mkdir -p "$out"
      cp ${./profile.ps1}        "$out/profile.ps1"
      cp ${starshipToml}         "$out/starship.toml"
      cp ${../terminal-help.md}  "$out/terminal-help.md"
      cp ${setupScript}          "$out/setup.ps1"
    '';

  # ── `hm_win`: thin wrapper — builds the bundle, then deploys it ─────
  # Deliberately carries NO reference to the generated files, so its
  # closure (and therefore `home-manager switch`) stays tiny; the bundle
  # is built only when this runs.
  mkHmWin = pkgs: pkgs.writeShellApplication {
    name = "hm_win";
    runtimeInputs = [ pkgs.coreutils pkgs.jq ];
    # SC2016: we deliberately pass single-quoted *PowerShell* expressions
    # (e.g. '$PROFILE') to pwsh.exe — they must NOT be expanded by bash.
    excludeShellChecks = [ "SC2016" ];
    text = ''
      if ! command -v wslpath >/dev/null 2>&1; then
        echo "hm_win: must be run inside WSL (wslpath not found)." >&2
        exit 1
      fi

      # --setup / -s: after deploying, also run setup.ps1 on Windows
      # (winget + Scoop installs). Off by default — deploying dotfiles is
      # fast and frequent; the installs are slow and idempotent, so you
      # only want them when the package list actually changed.
      run_setup=0
      for arg in "$@"; do
        case "$arg" in
          -s | --setup) run_setup=1 ;;
          -h | --help)
            echo "usage: hm_win [--setup]"
            echo "  (no args)   deploy the Nix-generated dotfiles to the Windows profile"
            echo "  --setup,-s  also run setup.ps1 (winget + Scoop installs) afterwards"
            exit 0
            ;;
          *)
            echo "hm_win: unknown argument: $arg (try --help)" >&2
            exit 2
            ;;
        esac
      done

      # Build the generated bundle on demand from the local checkout
      # (override with HM_WIN_FLAKE). Nothing here is pre-built by
      # home-manager switch.
      flake="''${HM_WIN_FLAKE:-$HOME/nixos}"
      echo "hm_win: building windows-dotfiles from $flake ..."
      src="$(nix build "$flake#windows-dotfiles" --no-link --print-out-paths | tail -1)"
      if [ -z "$src" ] || [ ! -d "$src" ]; then
        echo "hm_win: failed to build windows-dotfiles." >&2
        exit 1
      fi

      # Detect the Windows profile at RUNTIME via the Windows interop.
      # This is a normal shell query on your machine (NOT Nix eval), so
      # it needs no `--impure` and adapts to the real account name and an
      # OneDrive-redirected Documents folder. powershell.exe (5.1) always
      # exists; prefer pwsh.exe (7) if installed.
      psexe=""
      for c in pwsh.exe powershell.exe; do
        if command -v "$c" >/dev/null 2>&1; then psexe="$c"; break; fi
      done
      userprofile_win=""
      profile_win=""
      if [ -n "$psexe" ]; then
        userprofile_win="$("$psexe" -NoProfile -NonInteractive -Command '[Environment]::GetFolderPath("UserProfile")' 2>/dev/null | tr -d '\r\n')"
        profile_win="$("$psexe" -NoProfile -NonInteractive -Command '$PROFILE.CurrentUserAllHosts' 2>/dev/null | tr -d '\r\n')"
      fi
      if [ -z "''${userprofile_win}" ]; then
        userprofile_win="$(cmd.exe /c 'echo %USERPROFILE%' 2>/dev/null | tr -d '\r\n')"
      fi

      if [ -n "''${userprofile_win}" ]; then
        userprofile="$(wslpath -u "$userprofile_win")"
      elif [ -n "''${HM_WIN_USER:-}" ]; then
        # Interop unavailable but the user told us the account name.
        userprofile="$(wslpath -u "C:/Users/$HM_WIN_USER" 2>/dev/null || true)"
        if [ -z "$userprofile" ] || [ ! -d "$userprofile" ]; then
          userprofile="/mnt/c/Users/$HM_WIN_USER"
        fi
      else
        echo "hm_win: couldn't detect the Windows profile via the interop." >&2
        echo "       Set HM_WIN_USER=<your-windows-username> and re-run." >&2
        exit 1
      fi

      # PowerShell profile path: the real $PROFILE (handles OneDrive)
      # when interop is available, else the default Documents location.
      if [ -n "''${profile_win}" ]; then
        profile_path="$(wslpath -u "$profile_win")"
      else
        profile_path="$userprofile/Documents/PowerShell/profile.ps1"
      fi

      cfg="$userprofile/.config"
      nixwin="$cfg/nixwin"

      backup() {
        if [ -e "$1" ] && [ ! -L "$1" ]; then
          cp -f "$1" "$1.bak.$(date +%Y%m%d%H%M%S)"
          echo "  backed up: $1"
        fi
      }
      deploy() {
        mkdir -p "$(dirname "$2")"
        backup "$2"
        install -m 0644 "$1" "$2"
        echo "  deployed: $2"
      }

      echo "hm_win: deploying to $userprofile"
      deploy "$src/profile.ps1" "$profile_path"
      deploy "$src/starship.toml" "$cfg/starship.toml"
      deploy "$src/terminal-help.md" "$cfg/terminal-help.md"
      deploy "$src/setup.ps1" "$nixwin/setup.ps1"

      # Windows Terminal: set only the default font face/size, merged
      # into the existing settings.json with jq (non-destructive).
      # Keybindings are intentionally left at their defaults.
      shopt -s nullglob
      wt_found=0
      for s in "$userprofile"/AppData/Local/Packages/Microsoft.WindowsTerminal_*/LocalState/settings.json; do
        wt_found=1
        backup "$s"
        tmp="$(mktemp)"
        if jq '.profiles.defaults.font.face = "FantasqueSansM Nerd Font Mono"
               | .profiles.defaults.font.size = (.profiles.defaults.font.size // 11)' \
             "$s" > "$tmp" 2>/dev/null; then
          mv "$tmp" "$s"
          echo "  Windows Terminal font set: $s"
        else
          rm -f "$tmp"
          echo "  WARN: could not update $s (left unchanged)"
        fi
      done
      shopt -u nullglob
      if [ "$wt_found" -eq 0 ]; then
        echo "  (Windows Terminal settings.json not found; skipped font)"
      fi

      setup_win="$(wslpath -w "$nixwin/setup.ps1")"
      if [ "$run_setup" -eq 1 ]; then
        if [ -z "$psexe" ]; then
          echo "hm_win: --setup needs the Windows PowerShell interop, which wasn't found." >&2
          echo "       Run this manually in PowerShell: $setup_win" >&2
          exit 1
        fi
        echo ""
        echo "hm_win: running setup.ps1 on Windows ($psexe) ..."
        # -ExecutionPolicy Bypass: the generated script is unsigned.
        "$psexe" -NoProfile -ExecutionPolicy Bypass -File "$setup_win"
        echo ""
        echo "Done. Restart your terminal to pick up everything."
      else
        echo ""
        echo "Done deploying. To install/update the toolkit, either:"
        echo "  hm_win --setup            # run the installer from here, or"
        echo "  $setup_win   # run it yourself in PowerShell"
        echo "(winget + Scoop installs). Then restart your terminal."
      fi
    '';
  };
in
{
  flake.lib.starshipSettings = starshipSettings;

  flake.modules.homeManager.windows = { pkgs, ... }: {
    home.packages = [ (mkHmWin pkgs) ];
  };

  perSystem = { pkgs, ... }: {
    packages.windows-dotfiles = mkWindowsDotfiles pkgs;
  };
}
